#spring:
#  config:
#    activate:
#      on-profile: local
#  application:
#    name: RingRingRing
#  datasource:
#    url: jdbc:mysql://localhost:3306/ringdb
#    username: ringringring
#    password: ringpwd
#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url: ring-project-rds-mysql.chgkg6km2h80.ap-northeast-2.rds.amazonaws.com:3306/ringdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: admin
#    password: ringringring





